### ISSUE TITLE
Twitter cards aren't being generated

### ISSUE THREAD

**Issue by AninditaBasu** [ultralytics/mkdocs#44]
Thank you for this awesome plugin.

I've followed the instructions in the README of this project to enable and use it for my website written in Markdown.
The social card for LinkedIn is generated correctly, with the image and title being picked up from the page. However, the Twitter card is not getting generated. 

My set up is: Files are in Markdown with no front matter; the site generator is MkDocs and deployment is through a GitHub actions through the `gh-page`s branch. The relevant portion in the `mkdocs.yml` file is:

```
plugins:
    - search
    - macros
    - ultralytics:
        verbose: True
        enabled: True
        default_image: "https://aninditabasu.github.io/comparative-mythology/images/logo.jpg"
        add_desc: True
        add_image: True
        add_keywords: False
        add_share_buttons: False
        add_dates: False
        add_authors: False
```

The generated HTML pages also contain the correct `meta` tags
```
<meta content="Dragon killings" name="title"/>
<meta content="website" property="og:type"/>
<meta content="https://aninditabasu.github.io/comparative-mythology/myths/dragon_slaying" property="og:url"/>
<meta content="Dragon killings" property="og:title"/>
<meta content="Dragons are mythical monsters that look like giant reptiles. The etymology of the word suggests that dragon is derived from the Greek word drakōn, which means snake 1. Snakes have, from the earliest times, been feared because of their human-killing venomous bite. It was easy for the ancients to imagine anything fearsome and cruel to be a dragon, and any person overcoming or killing such a menace to be a hero, worthy of adulation." property="og:description"/>
<meta content="../../images/here_be_dragons.png" property="og:image"/>
<meta content="summary_large_image" property="twitter:card"/>
<meta content="https://aninditabasu.github.io/comparative-mythology/myths/dragon_slaying" property="twitter:url"/>
<meta content="Dragon killings" property="twitter:title"/>
<meta content="Dragons are mythical monsters that look like giant reptiles. The etymology of the word suggests that dragon is derived from the Greek word drakōn, which means snake 1. Snakes have, from the earliest times, been feared because of their human-killing venomous bite. It was easy for the ancients to imagine anything fearsome and cruel to be a dragon, and any person overcoming or killing such a menace to be a hero, worthy of adulation." property="twitter:description"/>
<meta content="../../images/here_be_dragons.png" property="twitter:image"/>
```

However, the social card for Twitter isn't getting generated (LinkedIn card is generated fine).

Please let me know what further info is needed to help debug this issue.
